server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  username:
  password:
  vhost:
  canalServerHost: localhost:11111
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://localhost:3306/schema?useUnicode=true
      username: admin
      password: password
  canalAdapters:
    - instance: example
      groups:
        - groupId: g1
          outerAdapters:
            - name: es7
              hosts: ${KAE_ES_HOST:localhost:9200}
              properties:
                mode: rest
#                security.auth:  #  only used for rest mode
                cluster.name: elasticsearch